# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f517864e3d56f332ccd2558fa3422192cd946ff75cd0c3d60e68d3058b2ece1f0a7e0d9c3c019432407f301356cc5318c630ae0b61ac03ce1f3ba1ac5ee82ece

test:
  secret_key_base: e53994c646ddd0dc099c444480e73e7ec8c7a86d429365217e8162301c24d85c8c6c04a84203f0cac3b04d70181493e47dd617c4c7a93a5f39b975fcd943ca1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
